import { StoreProduct, StoreSettings } from './StoreContext';

export interface NicheTemplate {
  id: string;
  name: string;
  badge: string;
  icon: string;
  coverImage: string;
  description: string;
  settings: Partial<StoreSettings>;
  products: StoreProduct[];
}

export const STORE_NICHES: Record<string, NicheTemplate> = {
  electronics: {
    id: 'electronics',
    name: 'أجهزة ذكية وإلكترونيات',
    badge: 'التقنية الحديثة',
    icon: 'Smartphone',
    coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    description: 'سماعات رأس لاسلكية، ساعات ذكية AMOLED، شواحن ماج سيف وملحقات فاخرة',
    settings: {
      storeName: 'متجر الرائد للتقنية',
      storeSlogan: 'الوجهة السعودية الأولى لأحدث الأجهزة الذكية والملحقات الفاخرة',
      logoUrl: '/store-default-logo.svg',
      themePreset: 'neon-phosphor',
      primaryColor: '#FFE600',
      accentColor: '#FFD700',
      headerBgColor: '#161205',
      pageBgColor: '#120E04',
      cardBgColor: '#1C1707',
      footerBgColor: '#0C0903',
      announcementText: 'عروض التقنية الكبرى: شحن مجاني لكافة مدن المملكة للطلبات فوق 300 ر.س مع كود TECH50',
    },
    products: [
      {
        id: 'prod-tech-1',
        name: 'سماعات الرأس اللاسلكية الاحترافية Pro Max Ultra',
        category: 'إلكترونيات',
        price: 349,
        oldPrice: 699,
        stock: 8,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
        description: 'صوت مكاني ثلاثي الأبعاد مع خاصية إلغاء الضوضاء الفائقة وبطارية تدوم حتى 40 ساعة.',
        badge: 'الأكثر مبيعاً',
        rating: 4.9,
        reviewsCount: 184,
        features: ['عزل ضوضاء فعال ANC', 'صوت نقي Hi-Res', 'ضمان سعودي سنتين', 'شحن سريع Type-C'],
        isFlashDeal: true,
      },
      {
        id: 'prod-tech-2',
        name: 'ساعة يد ذكية مقاومة للماء مع شاشة AMOLED وتتبع المؤشرات',
        category: 'ساعات',
        price: 260,
        oldPrice: 420,
        stock: 14,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        description: 'شاشة AMOLED فائقة الوضوح، قياس نبضات القلب ونسبة الأكسجين مع بطارية تدوم 7 أيام.',
        badge: 'توصيل سريع',
        rating: 4.8,
        reviewsCount: 95,
        features: ['شاشة AMOLED', 'مقاومة الماء IP68', 'مكالمات بلوتوث', 'مستشعرات دقيقة'],
        isFlashDeal: false,
      },
      {
        id: 'prod-tech-3',
        name: 'منصة شحن لاسلكي مغناطيسي 3 في 1 السريع 15W',
        category: 'إلكترونيات',
        price: 185,
        oldPrice: 290,
        stock: 19,
        image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
        description: 'شحن الآيفون والساعة والسماعة في نفس الوقت بأمان تام وبدون أسلاك فوضوية.',
        badge: 'عرض خاص',
        rating: 4.7,
        reviewsCount: 62,
        features: ['شحن MagSafe سريع', 'حماية ضد الحرارة الزائدة', 'تصميم ألمنيوم أنيق'],
        isFlashDeal: true,
      },
      {
        id: 'prod-tech-4',
        name: 'كاميرا مراقبة ذكية 4K للأماكن الخارجية مع رؤية ليلية ملونة',
        category: 'إلكترونيات',
        price: 390,
        oldPrice: 580,
        stock: 11,
        image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
        description: 'تتبع حركة ذكي بالذكاء الاصطناعي وتطبيق مباشر للجوال مع طاقة شمسية مدمجة.',
        badge: 'جديد',
        rating: 4.9,
        reviewsCount: 47,
        features: ['دقة 4K فائقة', 'لوح طاقة شمسية مدمج', 'إنذار ذكي مباشر'],
        isFlashDeal: false,
      },
    ]
  },
  perfumes: {
    id: 'perfumes',
    name: 'عطور وبخور شرقي فاخر',
    badge: 'نفحات ملكية',
    icon: 'Sparkles',
    coverImage: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80',
    description: 'دهن عود كمبودي معتق، مسك العروس الأبيض، لبان حوجري، ومباخر ملكية',
    settings: {
      storeName: 'دار العود والعنبر الملكي',
      storeSlogan: 'خلاصات العطور الشرقية الأصيلة وأندر أنواع العود المعتق',
      logoUrl: '/store-default-logo.svg',
      themePreset: 'neon-phosphor',
      primaryColor: '#FFE600',
      accentColor: '#FFD700',
      headerBgColor: '#161205',
      pageBgColor: '#120E04',
      cardBgColor: '#1C1707',
      footerBgColor: '#0C0903',
      announcementText: 'خصومات الموسم: دهن عود مجاني مع كل طلب فوق 400 ر.س مع كود ROYAL',
    },
    products: [
      {
        id: 'prod-perfume-1',
        name: 'عطر العود الملكي الفاخر - خلطة الشيوخ الخاصة 100 مل',
        category: 'عطور شرقية',
        price: 480,
        oldPrice: 850,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80',
        description: 'نفحات ملكية ساحرة تجمع بين دهن العود الكمبودي والعنبر والورد الطائفي بثبات استثنائي 72 ساعة.',
        badge: 'إصدار ملكي',
        rating: 5.0,
        reviewsCount: 230,
        features: ['ثبات 72 ساعة', 'دهن عود نقي 100%', 'صندوق خشبي جلدي فاخر'],
        isFlashDeal: true,
      },
      {
        id: 'prod-perfume-2',
        name: 'مخلط مسك الختام والحرير الأبيض 12 مل تولة كريستال كاملة',
        category: 'أدهان ومسك',
        price: 190,
        oldPrice: 320,
        stock: 18,
        image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80',
        description: 'رائحة النظافة والفخامة برائحة المسك الأبيض الخالص مع لمسات البودر والزهور البيضاء.',
        badge: 'الأكثر مبيعاً',
        rating: 4.9,
        reviewsCount: 175,
        features: ['مسك طبيعي نقي', 'ثبات ممتاز للملابس والجسم', 'زجاجة كريستال مذهبة'],
        isFlashDeal: false,
      },
      {
        id: 'prod-perfume-3',
        name: 'بخور لبان حوجري عماني فاخر درجة أولى مع رقائق عود موروكي',
        category: 'بخور ولبان',
        price: 135,
        oldPrice: 210,
        stock: 22,
        image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
        description: 'لبان حوجري أخضر نقي يعطر المنزل والمجالس بنفحات زكية تبعث على الراحة والسكينة.',
        badge: 'طبيعي 100%',
        rating: 4.8,
        reviewsCount: 94,
        features: ['لبان حوجري أخضر نقي', 'خالي من الشوائب', 'دخان كثيف ورائحة زكية'],
        isFlashDeal: true,
      },
    ]
  },
  abayas: {
    id: 'abayas',
    name: 'عبايات وأزياء راقية',
    badge: 'أناقة خليجية',
    icon: 'Crown',
    coverImage: '/images/store/saudi-black-abaya.jpg',
    description: 'عبايات كريب ملكي ياباني، قفاطين مناسبات ساترة، وطرح حرير خليجية فاخرة',
    settings: {
      storeName: 'بوتيك لورا للعبايات والأزياء',
      storeSlogan: 'تصاميم خليجية حصرية تجمع بين الأصالة والقصات العصرية الراقية والساترة',
      logoUrl: '/store-default-logo.svg',
      themePreset: 'neon-phosphor',
      primaryColor: '#FFE600',
      accentColor: '#FFD700',
      headerBgColor: '#161205',
      pageBgColor: '#120E04',
      cardBgColor: '#1C1707',
      footerBgColor: '#0C0903',
      announcementText: 'تشكيلة الموسم الجديد: شحن سريع لكافة مدن المملكة وطرحة هدية مع كل عباية بكود LORA',
    },
    products: [
      {
        id: 'prod-abaya-1',
        name: 'عباية كريب ملكي ياباني سوداء فاحمة بقصة كلوش وتطريز كم يدوي',
        category: 'عبايات مناسبات',
        price: 360,
        oldPrice: 580,
        stock: 9,
        image: '/images/store/saudi-black-abaya.jpg',
        description: 'قماش كريب ملكي ياباني أسود فاحم وبارد، ساتر وأنيق لا يحتاج كوي مستمر مع تطريز راقي على الأكمام وطرحة شيلة مطابقة.',
        badge: 'الأكثر طلباً',
        rating: 4.9,
        reviewsCount: 156,
        features: ['قماش كريب ياباني نخب أول', 'قصة كلوش انسيابية ساترة', 'طرحة مجانية متطابقة'],
        isFlashDeal: true,
      },
      {
        id: 'prod-abaya-2',
        name: 'عباية كاجوال عملية لنن بيج مع أزرار خشبية أنيقة',
        category: 'عبايات يومية',
        price: 240,
        oldPrice: 380,
        stock: 14,
        image: '/images/store/saudi-linen-abaya.jpg',
        description: 'مثالية للدوام والجامعة، قماش لنن بارد ومريح وخفيف للارتداء اليومي الساتر.',
        badge: 'عملية ومريحة',
        rating: 4.8,
        reviewsCount: 89,
        features: ['لنن طبيعي 100%', 'قصة مستقيمة مريحة', 'جيوب جانبية عملية'],
        isFlashDeal: false,
      },
      {
        id: 'prod-abaya-3',
        name: 'طقم قفطان حرير مطرز فاخر للمناسبات والأعياد',
        category: 'فساتين وقفاطين',
        price: 490,
        oldPrice: 790,
        stock: 6,
        image: '/images/store/saudi-luxury-kaftan.jpg',
        description: 'تصميم خليجي ملكي بألوان راقية وتفاصيل انسيابية ساترة ومحتشمة تناسب الأعياد والمناسبات.',
        badge: 'إصدار العيد',
        rating: 5.0,
        reviewsCount: 64,
        features: ['حرير شيفون ناعم', 'بطانة داخلية مريحة ساترة', 'تطريز يدوي متقن'],
        isFlashDeal: true,
      },
    ]
  },
  coffee: {
    id: 'coffee',
    name: 'محمصة وقهوة مختصة',
    badge: 'محاصيل فاخرة',
    icon: 'Coffee',
    coverImage: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    description: 'محاصيل بن إثيوبية وكولومبية، أدوات تقطير V60، ومطاحن احترافية',
    settings: {
      storeName: 'محمصة الرياض المختصة',
      storeSlogan: 'محاصيل بن فاخرة منتقاة بعناية لمحبي القهوة المقطرة والإسبريسو',
      logoUrl: '/store-default-logo.svg',
      themePreset: 'neon-phosphor',
      primaryColor: '#FFE600',
      accentColor: '#FFD700',
      headerBgColor: '#161205',
      pageBgColor: '#120E04',
      cardBgColor: '#1C1707',
      footerBgColor: '#0C0903',
      announcementText: 'عروض محبي القهوة: احصل على محصول مجاني عند شراء أي أداتي تقطير مع كود COFFEE15',
    },
    products: [
      {
        id: 'prod-coffee-1',
        name: 'محصول إثيوبيا قوجي الفاخر - معالجة مجففة 250 جم',
        category: 'محاصيل بن',
        price: 68,
        oldPrice: 85,
        stock: 25,
        image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=800&q=80',
        description: 'إيحاءات التوت الأسود، الفواكه الاستوائية، والياسمين بقوام مخملي استثنائي للـ V60.',
        badge: 'الأعلى تقييماً',
        rating: 5.0,
        reviewsCount: 312,
        features: ['محصول مختص 100%', 'تحميص أسبوعي طازج', 'مناسب للتقطير والإسبريسو'],
        isFlashDeal: true,
      },
      {
        id: 'prod-coffee-2',
        name: 'ماكينة تحضير قهوة الإسبريسو الإيطالية الاحترافية 20 بار',
        category: 'أجهزة قهوة',
        price: 520,
        oldPrice: 890,
        stock: 7,
        image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
        description: 'مضخة ضغط إيطالية قوية 20 بار مع عصا تبخير الحليب لصنع اللاتيه والكابتشينو برغوة حريرية.',
        badge: 'عرض حصري',
        rating: 4.9,
        reviewsCount: 142,
        features: ['ضغط 20 بار حقيقي', 'تسخين سريع ThermoBlock', 'عصا تبخير احترافية'],
        isFlashDeal: true,
      },
      {
        id: 'prod-coffee-3',
        name: 'بكج أدوات التقطير V60 المتكامل مع ميزان رقمي ومطحنة يدوية',
        category: 'أدوات تقطير',
        price: 240,
        oldPrice: 380,
        stock: 15,
        image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
        description: 'سيرفر زجاجي مقاوم للحرارة، قمع ترشيح سيراميك، مطحنة ستانلس ستيل، وميزان دقيق بالثواني.',
        badge: 'الأكثر طلباً',
        rating: 4.8,
        reviewsCount: 88,
        features: ['بكج متكامل 6 قطع', 'ميزان ذكي بدقة 0.1 جم', 'حقيبة سفر فاخرة'],
        isFlashDeal: false,
      },
      {
        id: 'prod-coffee-4',
        name: 'كوب قهوة سيراميك فاخر مصنوع يدوياً 250 مل',
        category: 'أكواب',
        price: 55,
        oldPrice: 80,
        stock: 30,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
        description: 'تصميم فني فريد بطبقات لونية دافئة تحافظ على حرارة مشروبك ونكهة القهوة الطبيعية.',
        badge: 'صناعة يدوية',
        rating: 4.9,
        reviewsCount: 65,
        features: ['سيراميك حراري نقي', 'ملمس طبيعي مريح', 'آمن لغسالة الصحون'],
        isFlashDeal: false,
      },
    ]
  },
  fitness: {
    id: 'fitness',
    name: 'مكملات ولياقة بدنية',
    badge: 'طاقة وأداء رياضي',
    icon: 'Flame',
    coverImage: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
    description: 'واي بروتين، كرياتين نقي، أحزمة رفع أثقال جلدية، ومعدات تمرين أصلية',
    settings: {
      storeName: 'متجر برو باور الرياضي',
      storeSlogan: 'مكملات رياضية أصلية 100% ومعدات تمرين احترافية لبناء القوة',
      logoUrl: '/store-default-logo.svg',
      themePreset: 'neon-phosphor',
      primaryColor: '#FFE600',
      accentColor: '#FFD700',
      headerBgColor: '#161205',
      pageBgColor: '#120E04',
      cardBgColor: '#1C1707',
      footerBgColor: '#0C0903',
      announcementText: 'عروض أبطال الرياضة: خصم 20% وشيكر مجاني على جميع باقات البروتين مع كود FIT20',
    },
    products: [
      {
        id: 'prod-fit-1',
        name: 'واي بروتين آيزوليت نقي 100% بنكهة الشوكولاتة 2 كجم',
        category: 'بروتين ومكملات',
        price: 295,
        oldPrice: 420,
        stock: 16,
        image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=800&q=80',
        description: '27 جم بروتين صافي لكل حصة مع صفر دهون وسكر مضاف وسرعة امتصاص فائقة للعضلات.',
        badge: 'الأعلى تقييماً',
        rating: 4.9,
        reviewsCount: 204,
        features: ['27g بروتين لكل سكوب', 'خالي من السكر والغلوتين', 'طعم غني ولذيذ'],
        isFlashDeal: true,
      },
      {
        id: 'prod-fit-2',
        name: 'كرياتين ميكرونايزد أحادي الهيدرات نقي 500 جم (100 حصة)',
        category: 'طاقة واستشفاء',
        price: 130,
        oldPrice: 190,
        stock: 24,
        image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=800&q=80',
        description: 'زيادة القوة البدنية وتحسين الأداء الرياضي وزيادة حجم الكتلة العضلية وسرعة الاستشفاء.',
        badge: 'الأكثر طلباً',
        rating: 5.0,
        reviewsCount: 310,
        features: ['كرياتين نقي 100%', 'سريع الذوبان', '100 حصة اقتصادية'],
        isFlashDeal: false,
      },
      {
        id: 'prod-fit-3',
        name: 'حزام رفع أثقال جلد طبيعي احترافي لحماية الظهر',
        category: 'معدات رياضية',
        price: 160,
        oldPrice: 250,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
        description: 'دعم قوي لمنطقة أسفل الظهر والعمود الفقري في تمارين القوة والسكوات.',
        badge: 'جودة معتمدة',
        rating: 4.8,
        reviewsCount: 115,
        features: ['جلد طبيعي متين', 'مشبك فولاذي مزدوج', 'حشوة قطنية مريحة للظهر'],
        isFlashDeal: true,
      },
    ]
  },
};
