const { PrismaClient } = require('@prisma/client');
const fs = require('fs');

const prisma = new PrismaClient();

async function main() {
  const contentPath = 'C:\\Users\\omara\\.gemini\\antigravity\\brain\\21349e53-e788-4533-a3cc-791c0153fd97\\.system_generated\\steps\\555\\content.md';
  const fullContent = fs.readFileSync(contentPath, 'utf8');

  // Skip the first few lines of the markdown file generated by the tool
  const lines = fullContent.split('\n');
  const actualContent = lines.slice(4).join('\n').trim();

  try {
    const newPost = await prisma.blogPost.create({
      data: {
        id: 'cmopkouj80000fb6p9gq3tjxu', // Try to use the same ID so the URL works if they kept the link
        title: 'The Future of Digital Marketing in Saudi Arabia',
        titleAr: 'مستقبل التسويق الرقمي في السعودية ورؤية 2030',
        slug: 'future-digital-marketing-saudi-arabia-2030',
        content: actualContent,
        contentAr: actualContent,
        excerpt: 'Discover how Vision 2030 is reshaping the digital marketing landscape in Saudi Arabia.',
        excerptAr: 'لم يعد السوق السعودي كما كان عليه قبل سنوات؛ فاليوم نحن نعيش نهضة تقنية غير مسبوقة تقودها رؤية 2030. تعرف على مستقبل التسويق الرقمي.',
        author: 'D-Arrow AI',
        category: 'Digital Marketing',
        categoryAr: 'التسويق الرقمي',
        date: new Date().toISOString().split('T')[0],
        time: new Date().toTimeString().split(' ')[0],
        readTime: 3,
        imageUrl: null,
        status: 'draft',
      }
    });
    console.log(`Successfully restored post as draft: ${newPost.id}`);
  } catch (error) {
    if (error.code === 'P2002') { // Unique constraint failed
      console.log('Post already exists, trying with auto-generated ID');
      const newPost2 = await prisma.blogPost.create({
        data: {
          title: 'The Future of Digital Marketing in Saudi Arabia',
          titleAr: 'مستقبل التسويق الرقمي في السعودية ورؤية 2030',
          slug: 'future-digital-marketing-saudi-arabia-2030-' + Date.now(),
          content: actualContent,
          contentAr: actualContent,
          excerpt: 'Discover how Vision 2030 is reshaping the digital marketing landscape in Saudi Arabia.',
          excerptAr: 'لم يعد السوق السعودي كما كان عليه قبل سنوات؛ فاليوم نحن نعيش نهضة تقنية غير مسبوقة تقودها رؤية 2030. تعرف على مستقبل التسويق الرقمي.',
          author: 'D-Arrow AI',
          category: 'Digital Marketing',
          categoryAr: 'التسويق الرقمي',
          date: new Date().toISOString().split('T')[0],
          time: new Date().toTimeString().split(' ')[0],
          readTime: 3,
          imageUrl: null,
          status: 'draft',
        }
      });
      console.log(`Successfully restored post as draft: ${newPost2.id}`);
    } else {
      console.error('Error restoring post:', error);
    }
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
